apiVersion: v1
kind: Pod
metadata:
  name: nginx-test2
  labels:
    env: test-env
spec:
  containers:
  - name: nginx
    image: nginx:latest
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "groupName"
    effect: "NoSchedule"