apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
    - name: container1
      image: nginx
      ports:
        - containerPort: 80
    - name: container2
      image: busybox
      command: ["/bin/sh", "-c"]
      args: ["while true; do echo 'Hello from Container 2'; sleep 10; done"]
