apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-demo

spec:
  containers:
  - name: basic-container
    image: registry.k8s.io/busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 20; sleep 1000
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 10